source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

pod 'AFNetworking', '~> 2.0'
pod 'AFOAuth2Manager'
pod 'Qiniu'
pod 'SDWebImage'
pod 'Reachability'
pod 'MBProgressHUD'
pod 'DateTools'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'CTAssetsPickerController'
pod 'QBPopupMenu'
pod 'Mantle', '~> 1.5'
pod 'FMDB', '~> 2.3'
pod 'MTLFMDBAdapter', :git => 'https://github.com/summerblue/MTLFMDBAdapter'
pod 'FMDBMigrationManager', '~> 1.3'
pod 'GVUserDefaults'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'UMengFeedback', '~> 2.3.4'
pod 'UMengSocial', '4.2.3'
pod 'QRCodeReaderViewController', :git => 'https://github.com/zhengjinghua-ext-forks/QRCodeReaderViewController.git'
pod 'UITextView+Placeholder'
pod 'pop', '~> 1.0'
pod 'FDFullscreenPopGesture', '1.1'
pod 'UITableView+FDTemplateLayoutCell'
pod 'UIActionSheet+Blocks'
pod 'Fabric'
pod 'Crashlytics'
pod 'DZNEmptyDataSet'